version: "3"

services:
  front:
    platform: linux/x86_64
    image: ghcr.io/benjamin-htr/tp_final_front:latest
    ports:
      - "8000:80"
    depends_on:
      - back

  back:
    platform: linux/x86_64
    image: ghcr.io/benjamin-htr/tp_final_back:latest
    ports:
      - "3000:3000"
